# Generated by Django 5.1.3 on 2024-12-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpcNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('variable', '变量'), ('object', '对象'), ('method', '方法')], max_length=20, verbose_name='节点类型')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('data_type', models.CharField(choices=[('double', '双精度浮点数(Double)'), ('float', '单精度浮点数(Float)'), ('int32', '32位整数(Int32)'), ('int64', '64位整数(Int64)'), ('uint32', '无符号32位整数(UInt32)'), ('uint64', '无符号64位整数(UInt64)'), ('boolean', '布尔值(Boolean)'), ('string', '字符串(String)'), ('datetime', '日期时间(DateTime)'), ('bytestring', '字节串(ByteString)')], default='double', max_length=20, verbose_name='数据类型')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='节点值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_manager.opcnode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': 'OPC UA节点',
                'verbose_name_plural': 'OPC UA节点',
            },
        ),
    ]
