# Generated by Django 5.1.3 on 2024-12-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcnode',
            name='variation_direction',
            field=models.IntegerField(default=1, verbose_name='变化方向'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_interval',
            field=models.IntegerField(default=1000, verbose_name='变化间隔(毫秒)'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_max',
            field=models.FloatField(blank=True, null=True, verbose_name='变化最大值'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_min',
            field=models.FloatField(blank=True, null=True, verbose_name='变化最小值'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_step',
            field=models.FloatField(blank=True, null=True, verbose_name='变化步长'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_type',
            field=models.CharField(choices=[('none', '不变化'), ('random', '随机变化'), ('linear', '线性变化'), ('discrete', '离散变化')], default='none', max_length=20, verbose_name='变化类型'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='variation_values',
            field=models.TextField(blank=True, null=True, verbose_name='离散值集合'),
        ),
        migrations.AlterField(
            model_name='opcnode',
            name='data_type',
            field=models.CharField(choices=[('double', '双精度浮点数(Double)'), ('float', '单精度浮点数(Float)'), ('int32', '32位整数(Int32)'), ('int64', '64位整数(Int64)'), ('uint16', '无符号16位整数(UInt16)'), ('uint32', '无符号32位整数(UInt32)'), ('uint64', '无符号64位整数(UInt64)'), ('boolean', '布尔值(Boolean)'), ('string', '字符串(String)'), ('datetime', '日期时间(DateTime)'), ('bytestring', '字节串(ByteString)'), ('array', '数组(Array)')], default='double', max_length=20, verbose_name='数据类型'),
        ),
    ]
