# Generated by Django 5.1.3 on 2024-12-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_manager', '0002_opcnode_variation_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcnode',
            name='variation_cycle',
            field=models.BooleanField(default=False, verbose_name='是否循环'),
        ),
        migrations.AlterField(
            model_name='opcnode',
            name='variation_type',
            field=models.CharField(choices=[('none', '不变化'), ('random', '随机变化'), ('linear', '线性变化'), ('discrete', '离散变化'), ('cycle', '循环变化')], default='none', max_length=20, verbose_name='变化类型'),
        ),
    ]
