# Generated by Django 5.1.4 on 2024-12-09 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_manager', '0004_opcnode_decimal_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('data_type', models.CharField(max_length=50, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('variation_type', models.CharField(choices=[('none', '无变化'), ('random', '随机变化'), ('linear', '线性变化'), ('sine', '正弦变化'), ('step', '步进变化')], max_length=20, verbose_name='变化类型')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('step', models.FloatField(blank=True, null=True, verbose_name='步长')),
                ('interval', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='变化间隔(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
        migrations.CreateModel(
            name='OpcServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('endpoint', models.CharField(max_length=200, verbose_name='服务器地址')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='端口号')),
                ('uri', models.CharField(max_length=200, verbose_name='服务器URI')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='允许匿名访问')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('min_publish_interval', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(100)], verbose_name='最小发布间隔(ms)')),
                ('default_namespace', models.CharField(blank=True, max_length=200, verbose_name='默认命名空间')),
                ('is_running', models.BooleanField(default=False, verbose_name='运行状态')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='最后启动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OPC服务器',
                'verbose_name_plural': 'OPC服务器',
            },
        ),
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('custom_name', models.CharField(blank=True, max_length=100, verbose_name='自定义名称')),
                ('custom_node_id', models.CharField(blank=True, max_length=100, verbose_name='自定义节点ID')),
                ('override_variation', models.BooleanField(default=False, verbose_name='覆盖变化设置')),
                ('custom_variation_type', models.CharField(blank=True, choices=[('none', '无变化'), ('random', '随机变化'), ('linear', '线性变化'), ('sine', '正弦变化'), ('step', '步进变化')], max_length=20, verbose_name='自定义变化类型')),
                ('custom_min_value', models.FloatField(blank=True, null=True, verbose_name='自定义最小值')),
                ('custom_max_value', models.FloatField(blank=True, null=True, verbose_name='自定义最大值')),
                ('custom_step', models.FloatField(blank=True, null=True, verbose_name='自定义步长')),
                ('custom_interval', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='自定义变化间隔(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_nodes', to='opcua_manager.node', verbose_name='关联节点')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_nodes', to='opcua_manager.opcserver', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '服务器节点',
                'verbose_name_plural': '服务器节点',
                'unique_together': {('server', 'node')},
            },
        ),
        migrations.DeleteModel(
            name='OpcNode',
        ),
    ]
